CREATE TABLE ACCOUNT (
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    BALANCE DECIMAL(19,4) NOT NULL,
    TREASURY BOOLEAN NOT NULL,
    PRIMARY KEY(ID)
);